
# Copy this file to streamlit_app/.streamlit/secrets.toml and fill in the values.
MONGODB_URI = "mongodb+srv://<user>:<pass>@<cluster>/?retryWrites=true&w=majority&appName=<name>"
MONGODB_DB = "ind320"
MONGODB_COLLECTION = "elhub_production"

# Optional: Astra (managed Cassandra) for Spark connector
# ASTRA_SECURE_BUNDLE_PATH = "/path/to/secure-connect-database.zip"
# ASTRA_CLIENT_ID = "<your_astra_client_id>"
# ASTRA_CLIENT_SECRET = "<your_astra_client_secret>"

# Elhub API
# ELHUB_API_BASE = "https://api.elhub.no/energy-data-api"
# ELHUB_API_TOKEN = "<paste your bearer token here>"
